frr defaults datacenter
hostname dpu-hbn-02
log stdout informational
!
! HBN model: per-VPC VRFs with L3VNIs, EVPN type-5 over the fabric.
vrf vrf-blue
 vni 2024535
exit-vrf
vrf vrf-green
 vni 2024525
exit-vrf
!
interface lo
 ip address 10.180.62.2/32
!
router bgp 65202
 bgp router-id 10.180.62.2
 no bgp ebgp-requires-policy
 neighbor 172.30.0.2 remote-as 65100
 neighbor 172.30.0.2 description tor-leaf-01
 neighbor 172.30.0.2 bfd
 !
 address-family ipv4 unicast
  redistribute connected
  neighbor 172.30.0.2 activate
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor 172.30.0.2 activate
  advertise-all-vni
 exit-address-family
!
router bgp 65202 vrf vrf-blue
 bgp router-id 10.180.62.2
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 !
 address-family l2vpn evpn
  rd 10.180.62.2:2
  advertise ipv4 unicast
 exit-address-family
!
router bgp 65202 vrf vrf-green
 bgp router-id 10.180.62.2
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 !
 address-family l2vpn evpn
  rd 10.180.62.2:3
  advertise ipv4 unicast
 exit-address-family
!
line vty