#!/usr/bin/env bash
# Durable demo seed — align the FRR fabric's L3VNIs to NICo's allocated VNIs.
#
# NICo auto-assigns a VNI to each VPC and REASSIGNS new ones on every DB reset,
# while the fabric needs a stable VNI per VRF. This is the bridge: it ensures
# vpc-blue/vpc-green exist in NICo, reads the VNIs NICo gave them, writes them
# to frr/vpc-vnis.env (consumed by docker-compose env_file), and recomposes the
# fabric so each DPU's vrf-blue/vrf-green table-id == the NICo VNI.
#
# Idempotent. Run this after any NICo DB reset, then ./pb-peer.sh. Requires
# grpcurl, jq, the nico-system kind cluster up.
set -euo pipefail
cd "$(dirname -- "${BASH_SOURCE[0]}")"

CERTS=/tmp/nico-certs
grpc() { grpcurl -insecure --cert "$CERTS/tls.crt" --key "$CERTS/tls.key" "$@"; }

echo "==== 1. gRPC access (port-forward + certs) ===="
if ! grep -q "Forwarding from" /tmp/nico-pf.log 2>/dev/null || ! lsof -i :1079 >/dev/null 2>&1; then
  pkill -f "port-forward -n nico-system" 2>/dev/null || true; sleep 1
  nohup kubectl port-forward -n nico-system deploy/nico-api 1079:1079 >/tmp/nico-pf.log 2>&1 &
  disown
fi
for i in $(seq 1 15); do grep -q "Forwarding from" /tmp/nico-pf.log 2>/dev/null && break; sleep 1; done
grep -q "Forwarding from" /tmp/nico-pf.log || { echo "port-forward failed:"; cat /tmp/nico-pf.log; exit 1; }
if [ ! -f "$CERTS/tls.crt" ]; then
  mkdir -p "$CERTS"
  kubectl exec -n nico-system deploy/nico-api -- \
    tar cf - -C /var/run/secrets/spiffe.io/..data . 2>/dev/null | tar xf - -C "$CERTS" 2>/dev/null || true
fi

vni_of() {  # $1=vpc name -> prints its NICo VNI (empty if absent)
  ./nico-cli.sh -f json vpc show 2>/dev/null | grep -v IGNORING \
    | jq -r --arg n "$1" '.vpcs[]? | select(.metadata.name==$n) | (.status.vni // .deprecatedVni)' | head -1
}
ensure_vpc() {  # $1=vpc name -> ensures it exists, prints its VNI
  local vni; vni=$(vni_of "$1")
  if [ -z "$vni" ] || [ "$vni" = "null" ]; then
    grpc -d "{\"metadata\":{\"name\":\"$1\"},\"tenantOrganizationId\":\"demo-org\"}" \
      localhost:1079 forge.Forge.CreateVpc >/dev/null
    sleep 1; vni=$(vni_of "$1")
  fi
  echo "$vni"
}

echo "==== 2. ensure demo VPCs exist in NICo, read allocated VNIs ===="
BLUE_VNI=$(ensure_vpc vpc-blue)
GREEN_VNI=$(ensure_vpc vpc-green)
[ -n "$BLUE_VNI" ] && [ -n "$GREEN_VNI" ] && [ "$BLUE_VNI" != null ] && [ "$GREEN_VNI" != null ] \
  || { echo "FAILED to get VNIs (blue=$BLUE_VNI green=$GREEN_VNI)"; exit 1; }
echo "vpc-blue  VNI=$BLUE_VNI"
echo "vpc-green VNI=$GREEN_VNI"

echo "==== 3. write fabric env_file (frr/vpc-vnis.env) ===="
cat > frr/vpc-vnis.env <<EOF
# NICo-allocated VPC VNIs — regenerated by pb-seed.sh. Do not hand-edit.
VPC_BLUE_VNI=$BLUE_VNI
VPC_GREEN_VNI=$GREEN_VNI
EOF
cat frr/vpc-vnis.env

echo "==== 3b. align frr.conf L3VNI stanzas to the NICo VNIs ===="
# frr.conf hardcodes the L3VNIs in its `vni <n>` stanzas (bgpd config, no env
# substitution), so patch them in place. Read the CURRENT values first so this
# is idempotent and works no matter what they were left at.
cur_blue=$(grep -oE 'vni [0-9]+' frr/dpu-hbn/frr.conf | awk 'NR==1{print $2}')
cur_green=$(grep -oE 'vni [0-9]+' frr/dpu-hbn/frr.conf | awk 'NR==2{print $2}')
for f in frr/dpu-hbn/frr.conf frr/dpu-hbn-2/frr.conf frr/tor-leaf/frr.conf; do
  [ -n "$cur_blue" ]  && sed -i '' "s/vni $cur_blue/vni $BLUE_VNI/g"  "$f"
  [ -n "$cur_green" ] && sed -i '' "s/vni $cur_green/vni $GREEN_VNI/g" "$f"
done
echo "frr.conf L3VNIs: blue ${cur_blue:-?}->$BLUE_VNI, green ${cur_green:-?}->$GREEN_VNI"

echo "==== 4. bring up fabric + warm-restart to apply VNIs ===="
# Ensure the containers exist / apply any compose changes (may recreate once).
( cd frr && docker compose up -d tor-leaf dpu-hbn dpu-hbn-2 ) ; sleep 6
# Warm restart (NOT --force-recreate): re-runs init-evpn.sh, which re-sources
# the mounted vpc-vnis.env, and reloads frr.conf — and, unlike recreate, does
# NOT trigger FRR's type-5 origination race. This is the whole reason the VNIs
# are volume-mounted rather than passed via env_file.
echo "   warm-restarting fabric nodes to apply VNIs..."
docker restart tor-leaf-01 dpu-hbn-01 dpu-hbn-02 >/dev/null
sleep 4
# Disable NIC offload on every fabric container. VXLAN checksum/segmentation
# offload does NOT survive a colima VM reboot — packets get encapsulated and
# emitted but silently dropped in transit (bare IP still works, so it looks
# baffling). Turning offload off restores forwarding and, done here, makes the
# demo robust to colima restarts. Must run after each (re)start — a restart
# recreates the veth with offload back ON.
echo "   disabling NIC offload on fabric (survives colima restarts)..."
for c in tor-leaf-01 dpu-hbn-01 dpu-hbn-02 gcp-router; do
  docker exec "$c" sh -c 'command -v ethtool >/dev/null || apk add --no-cache ethtool >/dev/null 2>&1 || true
    for i in $(ls /sys/class/net | grep -E "^eth"); do
      ethtool -K "$i" tx off rx off tso off gso off gro off >/dev/null 2>&1 || true
    done' 2>/dev/null || true
done
# Poll for the actual ready condition (deterministic, not a blind sleep): both
# DPUs must originate their instance-subnet EVPN type-5 route.
echo -n "   waiting for type-5 origination on both DPUs"
for t in $(seq 1 24); do
  sleep 3; echo -n "."
  b=$(docker exec dpu-hbn-01 vtysh -c 'show bgp l2vpn evpn' 2>/dev/null | grep -c '10.10.10.0' || true)
  g=$(docker exec dpu-hbn-02 vtysh -c 'show bgp l2vpn evpn' 2>/dev/null | grep -c '10.20.20.0' || true)
  [ "${b:-0}" -gt 0 ] && [ "${g:-0}" -gt 0 ] && { echo " ready (~$((t*3))s)"; break; }
done

echo "==== 5. verify: fabric VRF table-id == NICo VNI ===="
got=$(docker exec dpu-hbn-01 ip -d link show vrf-blue 2>/dev/null | grep -oE 'table [0-9]+' | awk '{print $2}')
echo "dpu-hbn-01 vrf-blue table=$got  (NICo vpc-blue VNI=$BLUE_VNI)"
[ "$got" = "$BLUE_VNI" ] && echo "ALIGNED ✓" || echo "MISMATCH ✗ (check init-evpn.sh / env_file)"
echo
echo "seed complete — now run ./pb-peer.sh for the peering money demo."
