// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the RackIssue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RackIssue{}

// RackIssue One unresolved problem somewhere in a Rack
type RackIssue struct {
	// Set when the issue belongs to a host
	MachineId NullableString `json:"machineId,omitempty"`
	// Set when the issue belongs to a Rack component rather than a host
	Component NullableString `json:"component,omitempty"`
	// Health source that reported it, or `rack-component` for a component state
	Source *string `json:"source,omitempty"`
	// Stable alert identifier
	Id *string `json:"id,omitempty"`
	// What within the host or component the alert points at
	Target NullableString `json:"target,omitempty"`
	// When the alert was first raised
	FirstObserved NullableString `json:"firstObserved,omitempty"`
	// Operator-facing description
	Message *string `json:"message,omitempty"`
}

// NewRackIssue instantiates a new RackIssue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRackIssue() *RackIssue {
	this := RackIssue{}
	return &this
}

// NewRackIssueWithDefaults instantiates a new RackIssue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRackIssueWithDefaults() *RackIssue {
	this := RackIssue{}
	return &this
}

// GetMachineId returns the MachineId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RackIssue) GetMachineId() string {
	if o == nil || IsNil(o.MachineId.Get()) {
		var ret string
		return ret
	}
	return *o.MachineId.Get()
}

// GetMachineIdOk returns a tuple with the MachineId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RackIssue) GetMachineIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MachineId.Get(), o.MachineId.IsSet()
}

// HasMachineId returns a boolean if a field has been set.
func (o *RackIssue) HasMachineId() bool {
	if o != nil && o.MachineId.IsSet() {
		return true
	}

	return false
}

// SetMachineId gets a reference to the given NullableString and assigns it to the MachineId field.
func (o *RackIssue) SetMachineId(v string) {
	o.MachineId.Set(&v)
}

// SetMachineIdNil sets the value for MachineId to be an explicit nil
func (o *RackIssue) SetMachineIdNil() {
	o.MachineId.Set(nil)
}

// UnsetMachineId ensures that no value is present for MachineId, not even an explicit nil
func (o *RackIssue) UnsetMachineId() {
	o.MachineId.Unset()
}

// GetComponent returns the Component field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RackIssue) GetComponent() string {
	if o == nil || IsNil(o.Component.Get()) {
		var ret string
		return ret
	}
	return *o.Component.Get()
}

// GetComponentOk returns a tuple with the Component field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RackIssue) GetComponentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Component.Get(), o.Component.IsSet()
}

// HasComponent returns a boolean if a field has been set.
func (o *RackIssue) HasComponent() bool {
	if o != nil && o.Component.IsSet() {
		return true
	}

	return false
}

// SetComponent gets a reference to the given NullableString and assigns it to the Component field.
func (o *RackIssue) SetComponent(v string) {
	o.Component.Set(&v)
}

// SetComponentNil sets the value for Component to be an explicit nil
func (o *RackIssue) SetComponentNil() {
	o.Component.Set(nil)
}

// UnsetComponent ensures that no value is present for Component, not even an explicit nil
func (o *RackIssue) UnsetComponent() {
	o.Component.Unset()
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *RackIssue) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RackIssue) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *RackIssue) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *RackIssue) SetSource(v string) {
	o.Source = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RackIssue) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RackIssue) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RackIssue) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *RackIssue) SetId(v string) {
	o.Id = &v
}

// GetTarget returns the Target field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RackIssue) GetTarget() string {
	if o == nil || IsNil(o.Target.Get()) {
		var ret string
		return ret
	}
	return *o.Target.Get()
}

// GetTargetOk returns a tuple with the Target field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RackIssue) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Target.Get(), o.Target.IsSet()
}

// HasTarget returns a boolean if a field has been set.
func (o *RackIssue) HasTarget() bool {
	if o != nil && o.Target.IsSet() {
		return true
	}

	return false
}

// SetTarget gets a reference to the given NullableString and assigns it to the Target field.
func (o *RackIssue) SetTarget(v string) {
	o.Target.Set(&v)
}

// SetTargetNil sets the value for Target to be an explicit nil
func (o *RackIssue) SetTargetNil() {
	o.Target.Set(nil)
}

// UnsetTarget ensures that no value is present for Target, not even an explicit nil
func (o *RackIssue) UnsetTarget() {
	o.Target.Unset()
}

// GetFirstObserved returns the FirstObserved field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RackIssue) GetFirstObserved() string {
	if o == nil || IsNil(o.FirstObserved.Get()) {
		var ret string
		return ret
	}
	return *o.FirstObserved.Get()
}

// GetFirstObservedOk returns a tuple with the FirstObserved field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RackIssue) GetFirstObservedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FirstObserved.Get(), o.FirstObserved.IsSet()
}

// HasFirstObserved returns a boolean if a field has been set.
func (o *RackIssue) HasFirstObserved() bool {
	if o != nil && o.FirstObserved.IsSet() {
		return true
	}

	return false
}

// SetFirstObserved gets a reference to the given NullableString and assigns it to the FirstObserved field.
func (o *RackIssue) SetFirstObserved(v string) {
	o.FirstObserved.Set(&v)
}

// SetFirstObservedNil sets the value for FirstObserved to be an explicit nil
func (o *RackIssue) SetFirstObservedNil() {
	o.FirstObserved.Set(nil)
}

// UnsetFirstObserved ensures that no value is present for FirstObserved, not even an explicit nil
func (o *RackIssue) UnsetFirstObserved() {
	o.FirstObserved.Unset()
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *RackIssue) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RackIssue) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *RackIssue) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *RackIssue) SetMessage(v string) {
	o.Message = &v
}

func (o RackIssue) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RackIssue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.MachineId.IsSet() {
		toSerialize["machineId"] = o.MachineId.Get()
	}
	if o.Component.IsSet() {
		toSerialize["component"] = o.Component.Get()
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.Target.IsSet() {
		toSerialize["target"] = o.Target.Get()
	}
	if o.FirstObserved.IsSet() {
		toSerialize["firstObserved"] = o.FirstObserved.Get()
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableRackIssue struct {
	value *RackIssue
	isSet bool
}

func (v NullableRackIssue) Get() *RackIssue {
	return v.value
}

func (v *NullableRackIssue) Set(val *RackIssue) {
	v.value = val
	v.isSet = true
}

func (v NullableRackIssue) IsSet() bool {
	return v.isSet
}

func (v *NullableRackIssue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRackIssue(val *RackIssue) *NullableRackIssue {
	return &NullableRackIssue{value: val, isSet: true}
}

func (v NullableRackIssue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRackIssue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
