// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 1.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the RackIssues type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RackIssues{}

// RackIssues Every unresolved issue in a Rack
type RackIssues struct {
	// ID of the Rack
	RackId *string `json:"rackId,omitempty"`
	// Number of issues in the list
	OpenCount *int32 `json:"openCount,omitempty"`
	// Number of hosts the Rack's expected build places in it
	Hosts *int32 `json:"hosts,omitempty"`
	// The issues
	Issues []RackIssue `json:"issues,omitempty"`
}

// NewRackIssues instantiates a new RackIssues object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRackIssues() *RackIssues {
	this := RackIssues{}
	return &this
}

// NewRackIssuesWithDefaults instantiates a new RackIssues object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRackIssuesWithDefaults() *RackIssues {
	this := RackIssues{}
	return &this
}

// GetRackId returns the RackId field value if set, zero value otherwise.
func (o *RackIssues) GetRackId() string {
	if o == nil || IsNil(o.RackId) {
		var ret string
		return ret
	}
	return *o.RackId
}

// GetRackIdOk returns a tuple with the RackId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RackIssues) GetRackIdOk() (*string, bool) {
	if o == nil || IsNil(o.RackId) {
		return nil, false
	}
	return o.RackId, true
}

// HasRackId returns a boolean if a field has been set.
func (o *RackIssues) HasRackId() bool {
	if o != nil && !IsNil(o.RackId) {
		return true
	}

	return false
}

// SetRackId gets a reference to the given string and assigns it to the RackId field.
func (o *RackIssues) SetRackId(v string) {
	o.RackId = &v
}

// GetOpenCount returns the OpenCount field value if set, zero value otherwise.
func (o *RackIssues) GetOpenCount() int32 {
	if o == nil || IsNil(o.OpenCount) {
		var ret int32
		return ret
	}
	return *o.OpenCount
}

// GetOpenCountOk returns a tuple with the OpenCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RackIssues) GetOpenCountOk() (*int32, bool) {
	if o == nil || IsNil(o.OpenCount) {
		return nil, false
	}
	return o.OpenCount, true
}

// HasOpenCount returns a boolean if a field has been set.
func (o *RackIssues) HasOpenCount() bool {
	if o != nil && !IsNil(o.OpenCount) {
		return true
	}

	return false
}

// SetOpenCount gets a reference to the given int32 and assigns it to the OpenCount field.
func (o *RackIssues) SetOpenCount(v int32) {
	o.OpenCount = &v
}

// GetHosts returns the Hosts field value if set, zero value otherwise.
func (o *RackIssues) GetHosts() int32 {
	if o == nil || IsNil(o.Hosts) {
		var ret int32
		return ret
	}
	return *o.Hosts
}

// GetHostsOk returns a tuple with the Hosts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RackIssues) GetHostsOk() (*int32, bool) {
	if o == nil || IsNil(o.Hosts) {
		return nil, false
	}
	return o.Hosts, true
}

// HasHosts returns a boolean if a field has been set.
func (o *RackIssues) HasHosts() bool {
	if o != nil && !IsNil(o.Hosts) {
		return true
	}

	return false
}

// SetHosts gets a reference to the given int32 and assigns it to the Hosts field.
func (o *RackIssues) SetHosts(v int32) {
	o.Hosts = &v
}

// GetIssues returns the Issues field value if set, zero value otherwise.
func (o *RackIssues) GetIssues() []RackIssue {
	if o == nil || IsNil(o.Issues) {
		var ret []RackIssue
		return ret
	}
	return o.Issues
}

// GetIssuesOk returns a tuple with the Issues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RackIssues) GetIssuesOk() ([]RackIssue, bool) {
	if o == nil || IsNil(o.Issues) {
		return []RackIssue{}, false
	}
	return o.Issues, true
}

// HasIssues returns a boolean if a field has been set.
func (o *RackIssues) HasIssues() bool {
	if o != nil && !IsNil(o.Issues) {
		return true
	}

	return false
}

// SetIssues gets a reference to the given []RackIssue and assigns it to the Issues field.
func (o *RackIssues) SetIssues(v []RackIssue) {
	o.Issues = v
}

func (o RackIssues) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RackIssues) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RackId) {
		toSerialize["rackId"] = o.RackId
	}
	if !IsNil(o.OpenCount) {
		toSerialize["openCount"] = o.OpenCount
	}
	if !IsNil(o.Hosts) {
		toSerialize["hosts"] = o.Hosts
	}
	if !IsNil(o.Issues) {
		toSerialize["issues"] = o.Issues
	}
	return toSerialize, nil
}

type NullableRackIssues struct {
	value *RackIssues
	isSet bool
}

func (v NullableRackIssues) Get() *RackIssues {
	return v.value
}

func (v *NullableRackIssues) Set(val *RackIssues) {
	v.value = val
	v.isSet = true
}

func (v NullableRackIssues) IsSet() bool {
	return v.isSet
}

func (v *NullableRackIssues) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRackIssues(val *RackIssues) *NullableRackIssues {
	return &NullableRackIssues{value: val, isSet: true}
}

func (v NullableRackIssues) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRackIssues) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
